version: "3.9"
services:
  test:
    image: "exercise-6"
    volumes:
      - .:/app/code
    command: python3 -m pytest /app/code
  run:
    image: "exercise-6"
    volumes:
      - .:/app/code
    command: /spark/bin/spark-submit /app/code/main.py